name: stvNet
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py37_0
  - astor=0.8.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cloudpickle=1.2.2=py_1
  - colorama=0.4.3=py_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37hfa6e2cd_0
  - dask-core=2.9.1=py_0
  - decorator=4.4.1=py_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.2=py37_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.9.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - imageio=2.6.1=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.16.0=py37_0
  - jpeg=9c=hfa6e2cd_1001
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37ha925a31_0
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_hf44288c_0
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libopencv=4.2.0=py37_2
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.11.2=h7bd577a_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.1.0=h56a325e_0
  - libwebp=1.0.2=hfa6e2cd_5
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.2=py37_1
  - matplotlib-base=3.1.2=py37h2981e6d_1
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - networkx=2.4=py_0
  - numpy=1.17.4=py37h4320e6b_0
  - numpy-base=1.17.4=py37hc3f5095_0
  - olefile=0.46=py37_0
  - opencv=4.2.0=py37_2
  - openssl=1.1.1g=he774522_0
  - opt_einsum=3.1.0=py_0
  - pandas=0.25.3=py37ha925a31_0
  - parso=0.6.1=py_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37hcc1f983_0
  - pip=19.3.1=py37_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.2=py37h33f27b4_0
  - py-opencv=4.2.0=py37h5ca1d4c_2
  - pygments=2.5.2=py_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.12.3=py37h6538335_1
  - pyreadline=2.1=py37_1
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37hc8d92b1_0
  - pywin32=227=py37he774522_1
  - pyzmq=18.1.1=py37ha925a31_0
  - qt=5.12.5=h7ef1ec2_0
  - scikit-image=0.16.2=py37he350917_0
  - scipy=1.3.2=py37h29ff71c_0
  - setuptools=42.0.2=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=gpu_py37h57d29ca_0
  - tensorflow-base=2.0.0=gpu_py37h390e234_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37he774522_0
  - traitlets=4.3.3=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.11.2=py37he774522_0
  - xz=5.2.4=h2fa13f4_4
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyyaml==5.3.1
prefix: C:\Users\Stephen\Anaconda3\envs\stvNet

